
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ANIO APELLIDO_MATERNO APELLIDO_PATERNO DIA ENTIDAD ESPACIO MES NOMBRE SEXO VALORcurp : nombre apellido_paterno apellido_materno dia mes anio sexo entidadnombre : NOMBRE VALORapellido_paterno : APELLIDO_PATERNO VALORapellido_materno : APELLIDO_MATERNO VALORdia : DIA VALORmes : MES VALORanio : ANIO VALORsexo : SEXO VALORentidad : ENTIDAD VALOR'
    
_lr_action_items = {'NOMBRE':([0,],[3,]),'$end':([1,22,25,],[0,-1,-9,]),'APELLIDO_PATERNO':([2,6,],[5,-2,]),'VALOR':([3,5,8,11,14,17,20,23,],[6,9,12,15,18,21,24,25,]),'APELLIDO_MATERNO':([4,9,],[8,-3,]),'DIA':([7,12,],[11,-4,]),'MES':([10,15,],[14,-5,]),'ANIO':([13,18,],[17,-6,]),'SEXO':([16,21,],[20,-7,]),'ENTIDAD':([19,24,],[23,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'curp':([0,],[1,]),'nombre':([0,],[2,]),'apellido_paterno':([2,],[4,]),'apellido_materno':([4,],[7,]),'dia':([7,],[10,]),'mes':([10,],[13,]),'anio':([13,],[16,]),'sexo':([16,],[19,]),'entidad':([19,],[22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> curp","S'",1,None,None,None),
  ('curp -> nombre apellido_paterno apellido_materno dia mes anio sexo entidad','curp',8,'p_curp','sintactico.py',20),
  ('nombre -> NOMBRE VALOR','nombre',2,'p_nombre','sintactico.py',26),
  ('apellido_paterno -> APELLIDO_PATERNO VALOR','apellido_paterno',2,'p_apellido_paterno','sintactico.py',30),
  ('apellido_materno -> APELLIDO_MATERNO VALOR','apellido_materno',2,'p_apellido_materno','sintactico.py',34),
  ('dia -> DIA VALOR','dia',2,'p_dia','sintactico.py',38),
  ('mes -> MES VALOR','mes',2,'p_mes','sintactico.py',42),
  ('anio -> ANIO VALOR','anio',2,'p_anio','sintactico.py',46),
  ('sexo -> SEXO VALOR','sexo',2,'p_sexo','sintactico.py',50),
  ('entidad -> ENTIDAD VALOR','entidad',2,'p_entidad','sintactico.py',54),
]
